"""add role id to users

Revision ID: 08c057148c95
Revises: 6c5e5dced5f3
Create Date: 2026-09-27 23:02:30.060994

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '08c057148c95'
down_revision: str | Sequence[str] | None = '6c5e5dced5f3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role_id', sa.String(length=36), nullable=True), schema='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role_id', schema='users')
    # ### end Alembic commands ###
