"""create users table

Revision ID: a2cc23e96838
Revises:
Create Date: 2026-09-25 14:34:41.778951

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "a2cc23e96838"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
